### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by kalihale** [CSC-CLU/CSCClub_Tetris#11]
Fix RGB colors of each piece

**Comment by Zrp200** [comment]
context
<img width="389" alt="image" src="https://user-images.githubusercontent.com/7078074/162126406-cde2167f-b33e-4735-8866-3d4d19d978d9.png">

**Comment by kalihale** [comment]
Complete with #[c4c8cf8](https://github.com/CSC-CLU/CSCClub_Tetris/commit/c4c8cf824e56d07dbf7ad1c03d9a5591bb2d2e84)
