### ISSUE TITLE
Detect when the game is over

### ISSUE THREAD

**Issue by Zrp200** [CSC-CLU/CSCClub_Tetris#15]
Currently the game just locks itself when there's no room. In reality the game should automatically stop at that point. Even better would be an indication that you lost.

**Comment by kalihale** [comment]
To do this, I assume the best way would be to check if the position the shape is created at is a valid position. Does that sound right?

**Comment by Zrp200** [comment]
Yeah pretty much. In addition, we'd need to have some post-game state (in other words a game over state) where pieces don't spawn anymore.
