### ISSUE TITLE
Row Clearing

### ISSUE THREAD

**Issue by sudo-Eric** [CSC-CLU/CSCClub_Tetris#4]
A check for completed rows must be performed whenever a piece is placed. The check would need to account for removing the cleared row and shifting all lines above the row down.
There can be multiple rows that are cleared at a time (1-4) and the cleared rows might not be consecutive. This needs to be accounted for as well.

**Comment by Zrp200** [comment]
I don't see how clearing a row would create conflicts with the row above it. The way I see this getting implemented is checking the affected rows and then doing the shifting of the grid.

**Comment by sudo-Eric** [comment]
Let me try to rephrase. Row clearing will ultimately be shifting the contents above the cleared row down. Consideration does need to be given to cases where there are multiple lines to be cleared, especially if they are nonconsecutive ([here](https://tetris.fandom.com/wiki/Line_clear#:~:text=with%20cascade%20gravity.-,Hurdle%20or%20Split,-In%20Tetris%20DS)).

**Comment by kalihale** [comment]
Row clearing implemented with commit #28511e18c40e82ac7d05035b4f80870f2f5b7008
