### ISSUE TITLE
Hold Piece

### ISSUE THREAD

**Issue by sudo-Eric** [CSC-CLU/CSCClub_Tetris#5]
A hold piece needs to be implemented. The hold piece is defined as follows:
current = currently falling piece (piece on the board)
next = the next piece to fall (the piece in the next piece box)
hold = piece in the holding box
- At the start of a game, the hold piece must be empty. The first attempt to swap the current and hold pieces will result in the current piece being placed in hold and the next piece being dropped.
- When the hold piece is not empty and a swap is initiated, the current piece will be placed in hold and the hold piece will be dropped onto the board.
- When a hold piece is dropped onto the board, it will act as if it were the next piece (starts at the top of the board).

**Comment by Zrp200** [comment]
So from what I can tell from this [this](https://tetris.fandom.com/wiki/Hold_piece), it should be displayed to the upper left of the board. Currently that space is being used by the preview space.

Would displaying it _under_ the preview work, or should we look into changing where the preview goes as well?

**Comment by sudo-Eric** [comment]
Traditionally the hold piece is on the left side of the board and the next piece is on the right. However, we can have them swapped as it is not as iconic or important to gameplay as other features we are working on.

**Comment by Zrp200** [comment]
@sudo-Eric Do we have an extra button for hold? I don't recall seeing it.

**Comment by sudo-Eric** [comment]
The select button will double as the hold button. If select doesn't end up being used for anything else, we can just print it a new "hold" label.

**Comment by Zrp200** [comment]
<img width="407" alt="image" src="https://user-images.githubusercontent.com/7078074/164073646-4f4e967b-526e-4234-8c29-626251a31e09.png">

Currently it looks like this, is this good? Also implementing moving the shape (roughly) to the center in this.

**Comment by sudo-Eric** [comment]
That looks good
